name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ thesuuri }} -p ${{ 4V)4U8,T2Haz9)M }}
      - name: Build Docker Image
        run: docker build -t thesuuri/reactjs-app .
      - name: Publish image to docker hub
        run: docker push thesuuri/reactjs-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull reactjs-app:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer reactjs-app
