name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t thesuuri/nodejs-app:latest .

      - name: Push Docker Image
        run: docker push thesuuri/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull thesuuri/nodejs-app:latest

      - name: Stop and Remove Old Container (if exists)
        run: |
          if [ "$(docker ps -aq -f name=nodejs-app-container)" ]; then
            docker rm -f nodejs-app-container
          fi

      - name: Run New Docker Container
        run: |
          docker run -d -p 3000:3000 \
            --name nodejs-app-container \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            thesuuri/nodejs-app:latest
