name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ thesuuri }} -p ${{ 4V)4U8,T2Haz9)M }}
      - name: Build Docker Image
        run: docker build -t thesuuri/nodejs-app  .
      - name: Publish Image to docker hub
        run: docker push thesuuri/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull thesuuri/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nodejs-app-container -e MONGO_PASSWORD= 'wj4JXgUHv73S3Tab' thesuuri/nodejs-app
