name: Deploy Node Application

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t thesuuri/nodejs-app:latest .

      - name: Publish Image to Docker Hub
        run: docker push thesuuri/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Pull Image from Docker Hub
        run: docker pull thesuuri/nodejs-app:latest

      - name: Delete Old Container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nodejs-app-container -e MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" thesuuri/nodejs-app:latest
